### ISSUE TITLE
The code doesn't work (module 'tensorflow' has no attribute 'Dimension')

### ISSUE THREAD

**Issue by saberkia** [yalharbi/StructuredNoiseInjection#1]
I tried to execute the code but I have the issue:

Traceback (most recent call last):
  File "pretrained_SNI.py", line 15, in <module>
    import dnnlib.tflib as tflib
  File "/home/tensor/Kython/StructuredNoiseInjection/dnnlib/tflib/__init__.py", line 8, in <module>
    from . import autosummary
  File "/home/tensor/Kython/StructuredNoiseInjection/dnnlib/tflib/autosummary.py", line 31, in <module>
    from . import tfutil
  File "/home/tensor/Kython/StructuredNoiseInjection/dnnlib/tflib/tfutil.py", line 34, in <module>
    def shape_to_list(shape: Iterable[tf.Dimension]) -> List[Union[int, None]]:

**AttributeError: module 'tensorflow' has no attribute 'Dimension'**

Ubuntu 18.4
Tensorflow 2.1.0
Python 3.6
Processor: Intel Core i7-5820K @ 3.30GHz
Memory: 32 GB 2400 MHz DDR4
Graphics: GeForce GTX Titan X

**Comment by yalharbi** [comment]
I think the issue is with the Tensorflow version.

The code works with Tensorflow 1.14
